version: '3'
services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: elmoyi
      MYSQL_DATABASE: farmacia_moyano
      MYSQL_USER: albert_enrique
      MYSQL_PASSWORD: felipe2887
    ports:
      - "4000:3306"

  app:
    build:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000